version: '3.8'

services:
  postgres:
    build: './database'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydb
    restart: always

  nats:
    image: "nats-streaming:0.25.2"
    restart: always

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.2.3"
    environment:
      - discovery.type=single-node
